language: ruby
rvm:
  - 1.9.3
  - 1.8.7
env:
  - CAPYBARA_DEFAULT_DRIVER=poltergeist

branches:
  only:
    - master
    - 0_1_x
install: sudo apt-get install xvfb firefox libqt4-dev libqtwebkit-dev
before_script:
  - 'bundle'
script: 'bundle exec rspec'


